By now, we can load datasets into tensors and manipulate these tensors with basic math-
ematical operations. To start building sophisticated models, we will also need a few tools from `linear algebra`. This section offers a gentle introduction to the most essential concepts,starting from scalar arithmetic and ramping up to matrix multiplication.

In [2]:
import torch
import numpy as np


## 1. Scalars

Most everyday mathematics consists of manipulating numbers one at a time. Formally, we
call these values scalars. For example, the temperature in Palo Alto is a balmy 72 degrees
Fahrenheit. If you wanted to convert the temperature to Celsius you would evaluate the
expression `c =[5/9]( f − 32)`, setting `f` to `72`. In this equation, the values 5, 9, and 32 are constant **scalars**. The variables `c` and `f` in general represent unknown scalars.


We denote scalars by ordinary lower-cased letters (e.g., x, y, and z) and the space of all
(continuous) real-valued scalars by `R`. For expedience, we will skip past rigorous defini-
tions of spaces: just remember that the expression `x ∈ R` is a formal way to say that `x`is a *real-valued scalar*. The symbol `∈` (pronounced “in”) denotes membership in a set.
For example, `x, y ∈ {0, 1}` indicates that `x` and `y` are variables that can only take values `0` or `1`.
Scalars are implemented as tensors that contain only one element. Below, we assign two scalars and perform the familiar addition,multiplication, division, and exponentiation op-erations.


In [3]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y


(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## 2. Vectors

For current purposes, you can think of a `vector`as a fixed-length array of scalars. As with their code counterparts, we call these *scalars* the elements of the `vector` (synonyms include entries and components).

When vectors represent examples from real-world datasets, their values hold some real-world significance.

For example,
1. if we were training a model to
predict the risk of a loan defaulting, we might associate each applicant with a vector whose
components correspond to quantities like their income, length of employment, or number of
previous defaults.
2. If we were studying the risk of heart attack, each vector might represent
a patient and its components might correspond to their most recent vital signs, cholesterol
levels, minutes of exercise per day, etc.

We denote vectors by bold lowercase letters, (e.g,x, y, and z).

In [4]:
x = torch.arange(3)
x


tensor([0, 1, 2])

We can refer to an element of a vector by using a subscript.

For example, x2 denotes the second element of x. Since x2 is a scalar, we do not bold it. By default, we visualize vectors by stacking their elements vertically.



In [5]:
x[2]

tensor(2)

To indicate that a vector contains n elements, we write x ∈ $R^n$ . Formally, we call n the
dimensionality of the vector. In code, this corresponds to the tensor’s length, accessible via
Python’s built-in len function.

In [6]:
len(x)

3

We can also access the length via the shape attribute. The shape is a tuple that indicates
a tensor’s length along each axis. Tensors with just one axis have shapes with just one
element.

In [8]:
x.shape

torch.Size([3])

Oftentimes, the word `“dimension”` gets overloaded to mean both the number of axes and the
length along a particular axis.

To avoid this confusion, we use order to refer to the number of axes and dimensionality exclusively to refer to the number of components.

## 3. Matrices

Just as scalars are $0^{th}$-order tensors and vectors are $1^{st}$-order tensors, matrices are $2^{nd}$-order tensors. We denote matrices by bold capital letters (e.g., X, Y, and Z), and represent them in code by tensors with two axes. The expression **A ∈ $R^{m×n}$** indicates that a matrix `A` contains `m × n` real-valued scalars, arranged as `m` rows and `n` columns. When`m = n`,we say that a matrix is square. Visually, we can illustrate any matrix as a table.

In code, we represent a matrix  **A ∈ $R^{m×n}$** by a $2^{nd}$-order tensor with shape `(m, n)`. We can convert any appropriately sized `m × n` tensor into an `m × n` matrix by passing the desired
shape to reshape:

In [10]:
A = torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

Sometimes we want to flip the axes. When we exchange a matrix’s rows and columns, the
result is called its `transpose`. Formally, we signify a matrix `A’s` transpose by $A^T$ and if
B = $A^T$, then $b_{ij}$ = $a_{ji}$ for all `i` and `j`.

In [11]:
A.T #Transpose of Matrix A

tensor([[0, 2, 4],
        [1, 3, 5]])

Symmetric matrices are the subset of square matrices that are equal to their own transposes:
**A** = **$A^T$** . The following matrix is symmetric:

In [12]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

Matrices are useful for representing datasets. Typically, rows correspond to individual
records and columns correspond to distinct attributes.