By now, we can load datasets into tensors and manipulate these tensors with basic math-
ematical operations. To start building sophisticated models, we will also need a few tools from `linear algebra`. This section offers a gentle introduction to the most essential concepts,starting from scalar arithmetic and ramping up to matrix multiplication.

In [1]:
import torch
import numpy as np


## 1. Scalars

Most everyday mathematics consists of manipulating numbers one at a time. Formally, we
call these values scalars. For example, the temperature in Palo Alto is a balmy 72 degrees
Fahrenheit. If you wanted to convert the temperature to Celsius you would evaluate the
expression `c =[5/9]( f − 32)`, setting `f` to `72`. In this equation, the values 5, 9, and 32 are constant **scalars**. The variables `c` and `f` in general represent unknown scalars.


We denote scalars by ordinary lower-cased letters (e.g., x, y, and z) and the space of all
(continuous) real-valued scalars by `R`. For expedience, we will skip past rigorous defini-
tions of spaces: just remember that the expression `x ∈ R` is a formal way to say that `x`is a *real-valued scalar*. The symbol `∈` (pronounced “in”) denotes membership in a set.
For example, `x, y ∈ {0, 1}` indicates that `x` and `y` are variables that can only take values `0` or `1`.
Scalars are implemented as tensors that contain only one element. Below, we assign two scalars and perform the familiar addition,multiplication, division, and exponentiation op-erations.


In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y


(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## 2. Vectors

For current purposes, you can think of a `vector`as a fixed-length array of scalars. As with their code counterparts, we call these *scalars* the elements of the `vector` (synonyms include entries and components).

When vectors represent examples from real-world datasets, their values hold some real-world significance.

For example,
1. if we were training a model to
predict the risk of a loan defaulting, we might associate each applicant with a vector whose
components correspond to quantities like their income, length of employment, or number of
previous defaults.
2. If we were studying the risk of heart attack, each vector might represent
a patient and its components might correspond to their most recent vital signs, cholesterol
levels, minutes of exercise per day, etc.

We denote vectors by bold lowercase letters, (e.g,x, y, and z).

In [3]:
x = torch.arange(3)
x


tensor([0, 1, 2])

We can refer to an element of a vector by using a subscript.

For example, x2 denotes the second element of x. Since x2 is a scalar, we do not bold it. By default, we visualize vectors by stacking their elements vertically.



In [4]:
x[2]

tensor(2)

To indicate that a vector contains n elements, we write x ∈ $R^n$ . Formally, we call n the
dimensionality of the vector. In code, this corresponds to the tensor’s length, accessible via
Python’s built-in len function.

In [5]:
len(x)

3

We can also access the length via the shape attribute. The shape is a tuple that indicates
a tensor’s length along each axis. Tensors with just one axis have shapes with just one
element.

In [6]:
x.shape

torch.Size([3])

Oftentimes, the word `“dimension”` gets overloaded to mean both the number of axes and the
length along a particular axis.

To avoid this confusion, we use order to refer to the number of axes and dimensionality exclusively to refer to the number of components.

## 3. Matrices

Just as scalars are $0^{th}$-order tensors and vectors are $1^{st}$-order tensors, matrices are $2^{nd}$-order tensors. We denote matrices by bold capital letters (e.g., X, Y, and Z), and represent them in code by tensors with two axes. The expression **A ∈ $R^{m×n}$** indicates that a matrix `A` contains `m × n` real-valued scalars, arranged as `m` rows and `n` columns. When`m = n`,we say that a matrix is square. Visually, we can illustrate any matrix as a table.

In code, we represent a matrix  **A ∈ $R^{m×n}$** by a $2^{nd}$-order tensor with shape `(m, n)`. We can convert any appropriately sized `m × n` tensor into an `m × n` matrix by passing the desired
shape to reshape:

In [7]:
A = torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

Sometimes we want to flip the axes. When we exchange a matrix’s rows and columns, the
result is called its `transpose`. Formally, we signify a matrix `A’s` transpose by $A^T$ and if
B = $A^T$, then $b_{ij}$ = $a_{ji}$ for all `i` and `j`.

In [8]:
A.T #Transpose of Matrix A

tensor([[0, 2, 4],
        [1, 3, 5]])

Symmetric matrices are the subset of square matrices that are equal to their own transposes:
**A** = **$A^T$** . The following matrix is symmetric:

In [9]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

Matrices are useful for representing datasets. Typically, rows correspond to individual
records and columns correspond to distinct attributes.

## 4. Tensors

While you can go far in your machine learning journey with only scalars, vectors, andmatrices, eventually you may need to work with higher-order tensors. **Tensors** give us a generic way of describing extensions to $n^{th-order}$ arrays. We call software objects of the tensor class “tensors” precisely because they too can have arbitrary numbers of axes. While it may be confusing to use the word tensor for both the mathematical object and its
realization in code, our meaning should usually be clear from context.

Tensors will play an important role while working with images. Images generally contain $3{rd}$ order tensor with axes corresponding to the height , width and channel. At each spatial location, the intensitiesd of each color are stacked along with the channel. Furthermore a collection of images is represented in code by $4^{th}$-order tensor, where distinct images are indexed along the first axis. Higher-order tensors are constructred , as were vectors and matries , by growing the number of shape components.

In [10]:
torch.arange(24).reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 5. Basic Properties of Tensor: 

### 1. Arthemetic Operation:
Scalars, vectors, matrices, and higher-order tensors all have some handy properties. For example, elementwise operations produce outputs that have the same shape as their operands.

In [11]:
A = torch.arange(6, dtype = torch.float32).reshape(2,3)
B = A.clone()

A, B ,A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

The elementwise product of two matrices is called their `Hadamard product` (denoted).We can spell out the entries of the Hadamard product of two matrices **A**,**B** **∈** **R**$^{m×n}$.

In [12]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

Adding or multiplying a scalar and a tensor produces a result with the same shape as
the original tensor. Here, each element of the tensor is added to (or multiplied by) the
scalar.

In [13]:
a = 2
X = torch.arange(24).reshape(2,3,4) # Two Tensors of 3*4 each
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 6.Reductions 

Often we wish to calculate the sum of a tensor's elements. To express the sum of the elements in a vector `x` of length `n` , we write $\sum_{i=1}^{n} x_i$. There is a simple function for it:

In [14]:
x = torch.arange(3, dtype = torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

To express sums over the elements of tensors of arbitrary shape, we simply sum over all its axes. For example, the sum of the elements of an`m` × `n` matrix `A` could be written
$\sum_{i=1}^{m}\sum_{j=1}^{n}a_{ij}$

In [15]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

By default, invoking the sum function *reduces* a tensor along all of its axes, eventually    producing a `scalar`. Our libraries also allow us to specify the axes along which the `tensor` should be reduced. To sum over all elements along the rows (`axis 0`), we specify `axis=0` in
**sum**. Since the input matrix reduces along axis 0 to generate the output vector, this axis is missing from the shape of the output.

In [16]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

Specifying `axis=1` will reduce the column dimension (`axis 1`) by summing up elements of
all the columns.

In [17]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

Reducing a matrix along both rows and columns via summation is equivalent to summing
up all the elements of the matrix.

In [18]:
A.sum(axis=[0,1]) == A.sum() #Same as A.sum()

tensor(True)

A related quantity is the *mean*, also called the *average*. We calculate the *mean* by dividing
the sum by the total number of elements. Because computing the mean is so common, it
gets a dedicated library function that works analogously to sum.

In [19]:
A.mean(), A.sum()/ A.numel()

(tensor(2.5000), tensor(2.5000))

Likewise, the function for calculating the mean can also reduce a tensor along specific
axes.

In [20]:
A, A.mean(axis=0), A.sum(axis=0)/ A.shape[0]

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([1.5000, 2.5000, 3.5000]),
 tensor([1.5000, 2.5000, 3.5000]))

In [21]:
A, A.mean(axis=1), A.sum(axis=1)/ A.shape[0]

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([1., 4.]),
 tensor([1.5000, 6.0000]))

## 7. Non-Reduction Sum

Sometims it can be useful to keep the number of axes unchanges when invoking the function for calculating sum or mean. This matters when we want to use the broadcast mechanism.

In [22]:
sum_A = A.sum(axis=1, keepdim=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

For instance , since `sum_A` keeps its two axes after summing each row, we can divide `A` by `sum_A` with broadcasting to create a matrix where each row sums up to 1.

In [23]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

If we want to calculate the cumulative sum of elements of `A` along some axis, say `axis=0`
(row by row), we can call the **cumsum** function. By design, this function does not reduce the input tensor along any axis.

In [24]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

## 8. Dot Products

So far we have performed element wise operations,sums and averages. And if this was all we could do , Linear algebra would not deserve its own section. Fortunately this is where things get more intersting.

One of the most fundamental operations is the dot product. Give two elements **x**, **y**  ∈ $R^{d}$ there *dot product*  $x^{T}$(also known as inner product (x,y)) is the sum over the products of the elements at the same position: $x^{T}y = \sum_{i=1}^{d}x_{i}y_{i}$

In [25]:
y = torch.ones(3, dtype = torch.float32)
x, y , torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

Equivalently, we can calculate the dot product of two vectors by performing an elementwise
multiplication followed by a sum:

In [26]:
torch.sum(x * y)

tensor(3.)

Dot products are useful in a wide range of contexts. For example, given some set of values, denoted by a vector **x** ∈ **$R^{n}$** and a set of weights, denoted by **w** ∈ **$R^{n}$** , the weighted
sum of the values in **x** according to the weights **w** could be expressed as the dot product **x**$^{T}$**w**. 


When the weights are nonnegative and sum to 1, i.e. ($\sum_{i=1}^{n}w_{i}$ = 1) ,the dot product expresses a *weighted average*. After normalizing two vectors to have unit length, the dot products express the cosine of the angle between them. Later in this section, we will formally introduce this notion of *length*.