# 1. Introduction:

Calculus plays an important role in deep learning in optmization of algorithms. But the process can be tedious as you start doing the calculation by hand and also becomes error-prone.

Fortunately all modern deep learning frameworks have a workaround by offering *automatic differantiation*(Also called *autograd*). As we pass data throught each successive function, the frameworl build *computational graph* that tracks each and how value depend on others. To calculate derivatives , automatic differantiation works backwards through this graph applying chain rule. The computational algorithm for applying the chain rule in this fashion is called *backpropogation*.

While autograd libraries have become a hot concern over the past decade, they have a
long history. In fact the earliest references to autograd date back over half of a century
(Wengert, 1964). The core ideas behind modern backpropagation date to a PhD thesis
from 1980 (Speelpenning, 1980) and were further developed in the late 1980s (Griewank,
1989).While backpropagation has become the default method for computing gradients,
it is not the only option. For instance, the Julia programming language employs forward
propagation (Revels et al., 2016). Before exploring methods, let’s first master the autograd
package.

In [1]:
import torch

# 2. A Simple Function

Let’s assume that we are interested in differentiating the function $y = 2x^{T}$ x with respect to the column vector x. To start, we assign x an initial value.

In [2]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

Before we calculate the gradient of y with respect to x, we need a place to store it. In
general, we avoid allocating new memory every time we take a derivative because deep
learning requires successively computing derivatives with respect to the same parameters
a great many times, and we might risk running out of memory. Note that the gradient of
a scalar-valued function with respect to a vector x is vector-valued with the same shape as
x.

In [3]:
# Can also create x = torch.arange(4.0, requires_grad=True)
x.requires_grad_(True)
x.grad # The gradient is None By default

We now calculate our function of x and assign the result to y.

In [4]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

We can now take the gradient of y with respect to x by calling its backward method. Next,
we can access the gradient via x’s grad attribute.

In [5]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

We already know that the gradient of the function $y = 2x^{T}$ with respect to x should be
4x. We can now verify that the automatic gradient computation and the expected result are
identical.

In [7]:
x.grad == 4*x

tensor([True, True, True, True])

Now let’s calculate another function of x and take its gradient. Note that PyTorch does not
automatically reset the gradient buffer when we record a new gradient. Instead, the new
gradient is added to the already-stored gradient. This behavior comes in handy when we
want to optimize the sum of multiple objective functions. To reset the gradient buffer, we
can call *x.grad.zero_()* as follows:

In [8]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad


tensor([1., 1., 1., 1.])